//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CHM_CLIENT_APP.CHMGA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CHMGACCESSoap", Namespace="http://192.168.1.213:10001/")]
    public partial class CHMGACCES : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback closeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMENUOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetACCES_MENUOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGROUPE_USERSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SELECT_FONCTION_USEROperationCompleted;
        
        private System.Threading.SendOrPostCallback ajouteMENUOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveAccesGroupUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveGroupUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateGroupUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback LOAD_FONCTION_USEROperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CHMGACCES() {
            this.Url = global::CHM_CLIENT_APP.Properties.Settings.Default.CHM_CLIENT_APP_CHMGA_CHMGACCES;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConnectionCompletedEventHandler ConnectionCompleted;
        
        /// <remarks/>
        public event closeCompletedEventHandler closeCompleted;
        
        /// <remarks/>
        public event getDateCompletedEventHandler getDateCompleted;
        
        /// <remarks/>
        public event GetMENUCompletedEventHandler GetMENUCompleted;
        
        /// <remarks/>
        public event GetACCES_MENUCompletedEventHandler GetACCES_MENUCompleted;
        
        /// <remarks/>
        public event GetGROUPE_USERSCompletedEventHandler GetGROUPE_USERSCompleted;
        
        /// <remarks/>
        public event SELECT_FONCTION_USERCompletedEventHandler SELECT_FONCTION_USERCompleted;
        
        /// <remarks/>
        public event ajouteMENUCompletedEventHandler ajouteMENUCompleted;
        
        /// <remarks/>
        public event saveAccesGroupUserCompletedEventHandler saveAccesGroupUserCompleted;
        
        /// <remarks/>
        public event saveGroupUserCompletedEventHandler saveGroupUserCompleted;
        
        /// <remarks/>
        public event updateGroupUserCompletedEventHandler updateGroupUserCompleted;
        
        /// <remarks/>
        public event LOAD_FONCTION_USERCompletedEventHandler LOAD_FONCTION_USERCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/Connection", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Connection() {
            this.Invoke("Connection", new object[0]);
        }
        
        /// <remarks/>
        public void ConnectionAsync() {
            this.ConnectionAsync(null);
        }
        
        /// <remarks/>
        public void ConnectionAsync(object userState) {
            if ((this.ConnectionOperationCompleted == null)) {
                this.ConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectionOperationCompleted);
            }
            this.InvokeAsync("Connection", new object[0], this.ConnectionOperationCompleted, userState);
        }
        
        private void OnConnectionOperationCompleted(object arg) {
            if ((this.ConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnectionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/close", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void close() {
            this.Invoke("close", new object[0]);
        }
        
        /// <remarks/>
        public void closeAsync() {
            this.closeAsync(null);
        }
        
        /// <remarks/>
        public void closeAsync(object userState) {
            if ((this.closeOperationCompleted == null)) {
                this.closeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncloseOperationCompleted);
            }
            this.InvokeAsync("close", new object[0], this.closeOperationCompleted, userState);
        }
        
        private void OncloseOperationCompleted(object arg) {
            if ((this.closeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.closeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/getDate", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime getDate() {
            object[] results = this.Invoke("getDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void getDateAsync() {
            this.getDateAsync(null);
        }
        
        /// <remarks/>
        public void getDateAsync(object userState) {
            if ((this.getDateOperationCompleted == null)) {
                this.getDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDateOperationCompleted);
            }
            this.InvokeAsync("getDate", new object[0], this.getDateOperationCompleted, userState);
        }
        
        private void OngetDateOperationCompleted(object arg) {
            if ((this.getDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDateCompleted(this, new getDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/GetMENU", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMENU() {
            object[] results = this.Invoke("GetMENU", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMENUAsync() {
            this.GetMENUAsync(null);
        }
        
        /// <remarks/>
        public void GetMENUAsync(object userState) {
            if ((this.GetMENUOperationCompleted == null)) {
                this.GetMENUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMENUOperationCompleted);
            }
            this.InvokeAsync("GetMENU", new object[0], this.GetMENUOperationCompleted, userState);
        }
        
        private void OnGetMENUOperationCompleted(object arg) {
            if ((this.GetMENUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMENUCompleted(this, new GetMENUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/GetACCES_MENU", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetACCES_MENU() {
            object[] results = this.Invoke("GetACCES_MENU", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetACCES_MENUAsync() {
            this.GetACCES_MENUAsync(null);
        }
        
        /// <remarks/>
        public void GetACCES_MENUAsync(object userState) {
            if ((this.GetACCES_MENUOperationCompleted == null)) {
                this.GetACCES_MENUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetACCES_MENUOperationCompleted);
            }
            this.InvokeAsync("GetACCES_MENU", new object[0], this.GetACCES_MENUOperationCompleted, userState);
        }
        
        private void OnGetACCES_MENUOperationCompleted(object arg) {
            if ((this.GetACCES_MENUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetACCES_MENUCompleted(this, new GetACCES_MENUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/GetGROUPE_USERS", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGROUPE_USERS(decimal codeCurrentGroupeUser) {
            object[] results = this.Invoke("GetGROUPE_USERS", new object[] {
                        codeCurrentGroupeUser});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGROUPE_USERSAsync(decimal codeCurrentGroupeUser) {
            this.GetGROUPE_USERSAsync(codeCurrentGroupeUser, null);
        }
        
        /// <remarks/>
        public void GetGROUPE_USERSAsync(decimal codeCurrentGroupeUser, object userState) {
            if ((this.GetGROUPE_USERSOperationCompleted == null)) {
                this.GetGROUPE_USERSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGROUPE_USERSOperationCompleted);
            }
            this.InvokeAsync("GetGROUPE_USERS", new object[] {
                        codeCurrentGroupeUser}, this.GetGROUPE_USERSOperationCompleted, userState);
        }
        
        private void OnGetGROUPE_USERSOperationCompleted(object arg) {
            if ((this.GetGROUPE_USERSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGROUPE_USERSCompleted(this, new GetGROUPE_USERSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/SELECT_FONCTION_USER", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SELECT_FONCTION_USER() {
            object[] results = this.Invoke("SELECT_FONCTION_USER", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SELECT_FONCTION_USERAsync() {
            this.SELECT_FONCTION_USERAsync(null);
        }
        
        /// <remarks/>
        public void SELECT_FONCTION_USERAsync(object userState) {
            if ((this.SELECT_FONCTION_USEROperationCompleted == null)) {
                this.SELECT_FONCTION_USEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSELECT_FONCTION_USEROperationCompleted);
            }
            this.InvokeAsync("SELECT_FONCTION_USER", new object[0], this.SELECT_FONCTION_USEROperationCompleted, userState);
        }
        
        private void OnSELECT_FONCTION_USEROperationCompleted(object arg) {
            if ((this.SELECT_FONCTION_USERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SELECT_FONCTION_USERCompleted(this, new SELECT_FONCTION_USERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/ajouteMENU", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ajouteMENU(System.Data.DataTable dtMENU) {
            this.Invoke("ajouteMENU", new object[] {
                        dtMENU});
        }
        
        /// <remarks/>
        public void ajouteMENUAsync(System.Data.DataTable dtMENU) {
            this.ajouteMENUAsync(dtMENU, null);
        }
        
        /// <remarks/>
        public void ajouteMENUAsync(System.Data.DataTable dtMENU, object userState) {
            if ((this.ajouteMENUOperationCompleted == null)) {
                this.ajouteMENUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnajouteMENUOperationCompleted);
            }
            this.InvokeAsync("ajouteMENU", new object[] {
                        dtMENU}, this.ajouteMENUOperationCompleted, userState);
        }
        
        private void OnajouteMENUOperationCompleted(object arg) {
            if ((this.ajouteMENUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ajouteMENUCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/saveAccesGroupUser", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void saveAccesGroupUser(string code_groupe, System.Data.DataTable dt) {
            this.Invoke("saveAccesGroupUser", new object[] {
                        code_groupe,
                        dt});
        }
        
        /// <remarks/>
        public void saveAccesGroupUserAsync(string code_groupe, System.Data.DataTable dt) {
            this.saveAccesGroupUserAsync(code_groupe, dt, null);
        }
        
        /// <remarks/>
        public void saveAccesGroupUserAsync(string code_groupe, System.Data.DataTable dt, object userState) {
            if ((this.saveAccesGroupUserOperationCompleted == null)) {
                this.saveAccesGroupUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveAccesGroupUserOperationCompleted);
            }
            this.InvokeAsync("saveAccesGroupUser", new object[] {
                        code_groupe,
                        dt}, this.saveAccesGroupUserOperationCompleted, userState);
        }
        
        private void OnsaveAccesGroupUserOperationCompleted(object arg) {
            if ((this.saveAccesGroupUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveAccesGroupUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/saveGroupUser", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void saveGroupUser(string designation, string description, decimal code_Privilège) {
            this.Invoke("saveGroupUser", new object[] {
                        designation,
                        description,
                        code_Privilège});
        }
        
        /// <remarks/>
        public void saveGroupUserAsync(string designation, string description, decimal code_Privilège) {
            this.saveGroupUserAsync(designation, description, code_Privilège, null);
        }
        
        /// <remarks/>
        public void saveGroupUserAsync(string designation, string description, decimal code_Privilège, object userState) {
            if ((this.saveGroupUserOperationCompleted == null)) {
                this.saveGroupUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveGroupUserOperationCompleted);
            }
            this.InvokeAsync("saveGroupUser", new object[] {
                        designation,
                        description,
                        code_Privilège}, this.saveGroupUserOperationCompleted, userState);
        }
        
        private void OnsaveGroupUserOperationCompleted(object arg) {
            if ((this.saveGroupUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveGroupUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/updateGroupUser", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateGroupUser(decimal code_fonction, string designation, string description, decimal code_Privilège) {
            this.Invoke("updateGroupUser", new object[] {
                        code_fonction,
                        designation,
                        description,
                        code_Privilège});
        }
        
        /// <remarks/>
        public void updateGroupUserAsync(decimal code_fonction, string designation, string description, decimal code_Privilège) {
            this.updateGroupUserAsync(code_fonction, designation, description, code_Privilège, null);
        }
        
        /// <remarks/>
        public void updateGroupUserAsync(decimal code_fonction, string designation, string description, decimal code_Privilège, object userState) {
            if ((this.updateGroupUserOperationCompleted == null)) {
                this.updateGroupUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateGroupUserOperationCompleted);
            }
            this.InvokeAsync("updateGroupUser", new object[] {
                        code_fonction,
                        designation,
                        description,
                        code_Privilège}, this.updateGroupUserOperationCompleted, userState);
        }
        
        private void OnupdateGroupUserOperationCompleted(object arg) {
            if ((this.updateGroupUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateGroupUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/LOAD_FONCTION_USER", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LOAD_FONCTION_USER(decimal code_fonction) {
            object[] results = this.Invoke("LOAD_FONCTION_USER", new object[] {
                        code_fonction});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LOAD_FONCTION_USERAsync(decimal code_fonction) {
            this.LOAD_FONCTION_USERAsync(code_fonction, null);
        }
        
        /// <remarks/>
        public void LOAD_FONCTION_USERAsync(decimal code_fonction, object userState) {
            if ((this.LOAD_FONCTION_USEROperationCompleted == null)) {
                this.LOAD_FONCTION_USEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnLOAD_FONCTION_USEROperationCompleted);
            }
            this.InvokeAsync("LOAD_FONCTION_USER", new object[] {
                        code_fonction}, this.LOAD_FONCTION_USEROperationCompleted, userState);
        }
        
        private void OnLOAD_FONCTION_USEROperationCompleted(object arg) {
            if ((this.LOAD_FONCTION_USERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LOAD_FONCTION_USERCompleted(this, new LOAD_FONCTION_USERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConnectionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void closeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getDateCompletedEventHandler(object sender, getDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetMENUCompletedEventHandler(object sender, GetMENUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMENUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMENUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetACCES_MENUCompletedEventHandler(object sender, GetACCES_MENUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetACCES_MENUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetACCES_MENUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetGROUPE_USERSCompletedEventHandler(object sender, GetGROUPE_USERSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGROUPE_USERSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGROUPE_USERSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SELECT_FONCTION_USERCompletedEventHandler(object sender, SELECT_FONCTION_USERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SELECT_FONCTION_USERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SELECT_FONCTION_USERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ajouteMENUCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void saveAccesGroupUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void saveGroupUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void updateGroupUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LOAD_FONCTION_USERCompletedEventHandler(object sender, LOAD_FONCTION_USERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LOAD_FONCTION_USERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LOAD_FONCTION_USERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591