//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CHM_CLIENT_APP.CHMMARQUE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CHM_MARQUESoap", Namespace="http://192.168.1.213:10001/")]
    public partial class CHM_MARQUE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback closeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDateSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListeMarqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback loadMarqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertMarqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateMarqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteMarqueOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CHM_MARQUE() {
            this.Url = global::CHM_CLIENT_APP.Properties.Settings.Default.CHM_CLIENT_APP_CHMMARQUE_CHM_MARQUE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConnectionCompletedEventHandler ConnectionCompleted;
        
        /// <remarks/>
        public event closeCompletedEventHandler closeCompleted;
        
        /// <remarks/>
        public event getDateSCompletedEventHandler getDateSCompleted;
        
        /// <remarks/>
        public event getListeMarqueCompletedEventHandler getListeMarqueCompleted;
        
        /// <remarks/>
        public event loadMarqueCompletedEventHandler loadMarqueCompleted;
        
        /// <remarks/>
        public event insertMarqueCompletedEventHandler insertMarqueCompleted;
        
        /// <remarks/>
        public event updateMarqueCompletedEventHandler updateMarqueCompleted;
        
        /// <remarks/>
        public event deleteMarqueCompletedEventHandler deleteMarqueCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/Connection", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Connection() {
            this.Invoke("Connection", new object[0]);
        }
        
        /// <remarks/>
        public void ConnectionAsync() {
            this.ConnectionAsync(null);
        }
        
        /// <remarks/>
        public void ConnectionAsync(object userState) {
            if ((this.ConnectionOperationCompleted == null)) {
                this.ConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectionOperationCompleted);
            }
            this.InvokeAsync("Connection", new object[0], this.ConnectionOperationCompleted, userState);
        }
        
        private void OnConnectionOperationCompleted(object arg) {
            if ((this.ConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnectionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/close", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void close() {
            this.Invoke("close", new object[0]);
        }
        
        /// <remarks/>
        public void closeAsync() {
            this.closeAsync(null);
        }
        
        /// <remarks/>
        public void closeAsync(object userState) {
            if ((this.closeOperationCompleted == null)) {
                this.closeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncloseOperationCompleted);
            }
            this.InvokeAsync("close", new object[0], this.closeOperationCompleted, userState);
        }
        
        private void OncloseOperationCompleted(object arg) {
            if ((this.closeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.closeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/getDateS", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime getDateS() {
            object[] results = this.Invoke("getDateS", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void getDateSAsync() {
            this.getDateSAsync(null);
        }
        
        /// <remarks/>
        public void getDateSAsync(object userState) {
            if ((this.getDateSOperationCompleted == null)) {
                this.getDateSOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDateSOperationCompleted);
            }
            this.InvokeAsync("getDateS", new object[0], this.getDateSOperationCompleted, userState);
        }
        
        private void OngetDateSOperationCompleted(object arg) {
            if ((this.getDateSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDateSCompleted(this, new getDateSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/getListeMarque", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getListeMarque() {
            object[] results = this.Invoke("getListeMarque", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getListeMarqueAsync() {
            this.getListeMarqueAsync(null);
        }
        
        /// <remarks/>
        public void getListeMarqueAsync(object userState) {
            if ((this.getListeMarqueOperationCompleted == null)) {
                this.getListeMarqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListeMarqueOperationCompleted);
            }
            this.InvokeAsync("getListeMarque", new object[0], this.getListeMarqueOperationCompleted, userState);
        }
        
        private void OngetListeMarqueOperationCompleted(object arg) {
            if ((this.getListeMarqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListeMarqueCompleted(this, new getListeMarqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/loadMarque", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable loadMarque(decimal CODE_MARQUE) {
            object[] results = this.Invoke("loadMarque", new object[] {
                        CODE_MARQUE});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void loadMarqueAsync(decimal CODE_MARQUE) {
            this.loadMarqueAsync(CODE_MARQUE, null);
        }
        
        /// <remarks/>
        public void loadMarqueAsync(decimal CODE_MARQUE, object userState) {
            if ((this.loadMarqueOperationCompleted == null)) {
                this.loadMarqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloadMarqueOperationCompleted);
            }
            this.InvokeAsync("loadMarque", new object[] {
                        CODE_MARQUE}, this.loadMarqueOperationCompleted, userState);
        }
        
        private void OnloadMarqueOperationCompleted(object arg) {
            if ((this.loadMarqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loadMarqueCompleted(this, new loadMarqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/insertMarque", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT_QUERY insertMarque(string REF_MARQUE, string DESIGNATION_MARQUE, string DESCRIPTION_MARQUE) {
            object[] results = this.Invoke("insertMarque", new object[] {
                        REF_MARQUE,
                        DESIGNATION_MARQUE,
                        DESCRIPTION_MARQUE});
            return ((RESULT_QUERY)(results[0]));
        }
        
        /// <remarks/>
        public void insertMarqueAsync(string REF_MARQUE, string DESIGNATION_MARQUE, string DESCRIPTION_MARQUE) {
            this.insertMarqueAsync(REF_MARQUE, DESIGNATION_MARQUE, DESCRIPTION_MARQUE, null);
        }
        
        /// <remarks/>
        public void insertMarqueAsync(string REF_MARQUE, string DESIGNATION_MARQUE, string DESCRIPTION_MARQUE, object userState) {
            if ((this.insertMarqueOperationCompleted == null)) {
                this.insertMarqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertMarqueOperationCompleted);
            }
            this.InvokeAsync("insertMarque", new object[] {
                        REF_MARQUE,
                        DESIGNATION_MARQUE,
                        DESCRIPTION_MARQUE}, this.insertMarqueOperationCompleted, userState);
        }
        
        private void OninsertMarqueOperationCompleted(object arg) {
            if ((this.insertMarqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertMarqueCompleted(this, new insertMarqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/updateMarque", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT_QUERY updateMarque(decimal CODE_MARQUE, string DESIGNATION_MARQUE, string DESCRIPTION_MARQUE) {
            object[] results = this.Invoke("updateMarque", new object[] {
                        CODE_MARQUE,
                        DESIGNATION_MARQUE,
                        DESCRIPTION_MARQUE});
            return ((RESULT_QUERY)(results[0]));
        }
        
        /// <remarks/>
        public void updateMarqueAsync(decimal CODE_MARQUE, string DESIGNATION_MARQUE, string DESCRIPTION_MARQUE) {
            this.updateMarqueAsync(CODE_MARQUE, DESIGNATION_MARQUE, DESCRIPTION_MARQUE, null);
        }
        
        /// <remarks/>
        public void updateMarqueAsync(decimal CODE_MARQUE, string DESIGNATION_MARQUE, string DESCRIPTION_MARQUE, object userState) {
            if ((this.updateMarqueOperationCompleted == null)) {
                this.updateMarqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateMarqueOperationCompleted);
            }
            this.InvokeAsync("updateMarque", new object[] {
                        CODE_MARQUE,
                        DESIGNATION_MARQUE,
                        DESCRIPTION_MARQUE}, this.updateMarqueOperationCompleted, userState);
        }
        
        private void OnupdateMarqueOperationCompleted(object arg) {
            if ((this.updateMarqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateMarqueCompleted(this, new updateMarqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/deleteMarque", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULT_QUERY deleteMarque(decimal CODE_MARQUE) {
            object[] results = this.Invoke("deleteMarque", new object[] {
                        CODE_MARQUE});
            return ((RESULT_QUERY)(results[0]));
        }
        
        /// <remarks/>
        public void deleteMarqueAsync(decimal CODE_MARQUE) {
            this.deleteMarqueAsync(CODE_MARQUE, null);
        }
        
        /// <remarks/>
        public void deleteMarqueAsync(decimal CODE_MARQUE, object userState) {
            if ((this.deleteMarqueOperationCompleted == null)) {
                this.deleteMarqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteMarqueOperationCompleted);
            }
            this.InvokeAsync("deleteMarque", new object[] {
                        CODE_MARQUE}, this.deleteMarqueOperationCompleted, userState);
        }
        
        private void OndeleteMarqueOperationCompleted(object arg) {
            if ((this.deleteMarqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteMarqueCompleted(this, new deleteMarqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.1.213:10001/")]
    public partial class RESULT_QUERY {
        
        private string cODEField;
        
        private bool okField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        public bool OK {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
        
        /// <remarks/>
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConnectionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void closeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getDateSCompletedEventHandler(object sender, getDateSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDateSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDateSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getListeMarqueCompletedEventHandler(object sender, getListeMarqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListeMarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListeMarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void loadMarqueCompletedEventHandler(object sender, loadMarqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loadMarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loadMarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void insertMarqueCompletedEventHandler(object sender, insertMarqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertMarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertMarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT_QUERY Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT_QUERY)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void updateMarqueCompletedEventHandler(object sender, updateMarqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateMarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateMarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT_QUERY Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT_QUERY)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void deleteMarqueCompletedEventHandler(object sender, deleteMarqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteMarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteMarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULT_QUERY Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULT_QUERY)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591