CREATE TABLE [dbo].[ACCES_MENU] (
    [MENU]        NVARCHAR (50) NOT NULL,
    [CODE_GROUPE] DECIMAL (18)  NOT NULL,
    [VISIBLITE]   BIT           NOT NULL,
    CONSTRAINT [PK_ACCES_MENU] PRIMARY KEY CLUSTERED ([MENU] ASC, [CODE_GROUPE] ASC),
    CONSTRAINT [FK_ACCES_MENU_GROUPE_USERS] FOREIGN KEY ([CODE_GROUPE]) REFERENCES [dbo].[FONCTION_UTILISATEUR] ([CODE_FONCTION_USER]),
    CONSTRAINT [FK_ACCES_MENU_MENU] FOREIGN KEY ([MENU]) REFERENCES [dbo].[MENU] ([CODE_MENU])
);


GO
ALTER TABLE [dbo].[ACCES_MENU] NOCHECK CONSTRAINT [FK_ACCES_MENU_GROUPE_USERS];


GO
ALTER TABLE [dbo].[ACCES_MENU] NOCHECK CONSTRAINT [FK_ACCES_MENU_MENU];

