CREATE TABLE [dbo].[ATTACHE_BR_CMD_FR] (
    [CODE_BR_FR]                NVARCHAR (12) NOT NULL,
    [CODE_COMMANDE_FOURNISSEUR] NVARCHAR (12) NOT NULL,
    CONSTRAINT [FK_ATTACHE_BR_CMD_FR_COMMANDE_FOURNISSEUR] FOREIGN KEY ([CODE_COMMANDE_FOURNISSEUR]) REFERENCES [dbo].[COMMANDE_FOURNISSEUR] ([CODE_COMMANDE_FOURNISSEUR])
);


GO
ALTER TABLE [dbo].[ATTACHE_BR_CMD_FR] NOCHECK CONSTRAINT [FK_ATTACHE_BR_CMD_FR_COMMANDE_FOURNISSEUR];

