CREATE TABLE [dbo].[BON_DE_LIVRAISON] (
    [CODE_B_LIV]    NVARCHAR (20)   NOT NULL,
    [DATE_B_LIV]    DATETIME        NOT NULL,
    [CODE_CLIENT]   DECIMAL (18)    NOT NULL,
    [CODE_COMMANDE] NVARCHAR (25)   NOT NULL,
    [CODE_USER]     DECIMAL (18)    NOT NULL,
    [SOMME_B_LIV]   DECIMAL (18, 3) NULL,
    [FACTURED]      BIT             NULL,
    [PREPARED]      BIT             NULL,
    [LIVRE]         BIT             NULL,
    [CODE_MAG]      DECIMAL (18)    NULL,
    [ANNULE]        BIT             NULL,
    [CODE_FACTURE]  NVARCHAR (25)   CONSTRAINT [DF_BON_DE_LIVRAISON_CODE_FACTURE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_BON_DE_LIVRAISON] PRIMARY KEY CLUSTERED ([CODE_B_LIV] ASC),
    CONSTRAINT [FK_BON_DE_LIVRAISON_CLIENT] FOREIGN KEY ([CODE_CLIENT]) REFERENCES [dbo].[CLIENT] ([CODE_CLIENT]),
    CONSTRAINT [FK_BON_DE_LIVRAISON_UTILISATEUR] FOREIGN KEY ([CODE_USER]) REFERENCES [dbo].[UTILISATEUR] ([CODE_USER])
);


GO
ALTER TABLE [dbo].[BON_DE_LIVRAISON] NOCHECK CONSTRAINT [FK_BON_DE_LIVRAISON_CLIENT];


GO
ALTER TABLE [dbo].[BON_DE_LIVRAISON] NOCHECK CONSTRAINT [FK_BON_DE_LIVRAISON_UTILISATEUR];

