CREATE TABLE [dbo].[BON_RETOUR_CLIENT] (
    [CODE_BRETOUR_CLIENT] NVARCHAR (20)   NOT NULL,
    [DATE_BRETOUR_CLIENT] DATETIME        NOT NULL,
    [CODE_USER]           DECIMAL (18)    NOT NULL,
    [MNT_BRETOUR]         DECIMAL (18, 3) NOT NULL,
    [CODE_FACTURE]        NVARCHAR (25)   NOT NULL,
    [CODE_MAG]            DECIMAL (18)    NOT NULL,
    CONSTRAINT [PK_BON_RETOUR_CLIENT] PRIMARY KEY CLUSTERED ([CODE_BRETOUR_CLIENT] ASC)
);

