CREATE TABLE [dbo].[CATEGORIE] (
    [CODE_CATEG]        DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [LIB_CATEG]         NVARCHAR (50)  NOT NULL,
    [DESCRIPTION_CATEG] NVARCHAR (MAX) NULL,
    [CODE_FAMILLE]      DECIMAL (18)   CONSTRAINT [DF_CATEGORIE_CODE_FAMILLE] DEFAULT ('1') NOT NULL,
    [REF_CATEG]         NVARCHAR (3)   CONSTRAINT [DF_CATEGORIE_REF_CATEG] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_CATEGORIE] PRIMARY KEY CLUSTERED ([CODE_CATEG] ASC),
    CONSTRAINT [FK_CATEGORIE_FAMILLE] FOREIGN KEY ([CODE_FAMILLE]) REFERENCES [dbo].[FAMILLE] ([CODE_FAMILLE])
);

