CREATE TABLE [dbo].[CLIENT] (
    [CODE_CLIENT]        DECIMAL (18)    NOT NULL,
    [REF_CLIENT]         NVARCHAR (MAX)  NOT NULL,
    [RS_CLIENT]          NVARCHAR (MAX)  NOT NULL,
    [ADRESSE_CLIENT]     NVARCHAR (MAX)  NULL,
    [CP_CLIENT]          NVARCHAR (MAX)  NULL,
    [TEL_CLIENT]         NVARCHAR (MAX)  NULL,
    [FAX_CLIENT]         NVARCHAR (MAX)  NULL,
    [EMAIL_CLIENT]       NVARCHAR (MAX)  NULL,
    [EXO_CLIENT]         BIT             NULL,
    [ATTEST_EXO_CLIENT]  NVARCHAR (MAX)  NULL,
    [CODE_DOUANE_CLIENT] NVARCHAR (MAX)  NULL,
    [CODE_TVA_CLIENT]    NVARCHAR (MAX)  NULL,
    [ETAT_CLIENT]        BIT             NOT NULL,
    [COMPTE]             BIT             CONSTRAINT [DF_CLIENT_COMPTE] DEFAULT ('false') NULL,
    [VILLE_CLIENT]       NVARCHAR (MAX)  CONSTRAINT [DF_CLIENT_VILLE_CLIENT] DEFAULT ('') NULL,
    [PAYS_CLIENT]        NVARCHAR (MAX)  CONSTRAINT [DF_CLIENT_PAYS_CLIENT] DEFAULT ('') NULL,
    [MAX_CREDIT]         DECIMAL (18, 3) CONSTRAINT [DF_CLIENT_MAX_CREDIT] DEFAULT ((0)) NOT NULL,
    [TEL2_CLIENT]        NVARCHAR (MAX)  CONSTRAINT [DF_CLIENT_TEL2_CLIENT] DEFAULT ('') NULL,
    [RESP_CLIENT]        NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_CLIENT] PRIMARY KEY CLUSTERED ([CODE_CLIENT] ASC)
);

