CREATE TABLE [dbo].[CLIENTS$] (
    [TYPE_CLIENT]  NVARCHAR (255) NULL,
    [CODE_CLIENT]  DECIMAL (18)   NULL,
    [REF_CLIENT]   FLOAT (53)     NULL,
    [RS_CLIENT]    NVARCHAR (255) NULL,
    [RESP_CLIENT]  NVARCHAR (255) NULL,
    [TEL_CLIENT]   NVARCHAR (255) NULL,
    [TEL2_CLIENT]  NVARCHAR (255) NULL,
    [EMAIL_CLIENT] NVARCHAR (255) NULL
);

