CREATE TABLE [dbo].[COMMANDE_FOURNISSEUR] (
    [CODE_COMMANDE_FOURNISSEUR]            NVARCHAR (12)  NOT NULL,
    [DATE_COMMANDE_FOURNISSEUR]            DATETIME       NOT NULL,
    [CODE_USER]                            DECIMAL (18)   NOT NULL,
    [PRIORITE_COMMANDE_FOURNISSEUR]        BIT            NULL,
    [DATE_EXPIRATION_COMMANDE_FOURNISSEUR] DATETIME       CONSTRAINT [DF_COMMANDE_FOURNISSEUR_DATE_EXPIRATION_COMMANDE_FOURNISSEUR] DEFAULT ('01/01/1900') NULL,
    [CODE_FOURNISSEUR]                     DECIMAL (18)   NOT NULL,
    [ANNEE_CMDFR]                          INT            NOT NULL,
    [MOIS_CMDFR]                           INT            NOT NULL,
    [CODE_MAG]                             DECIMAL (18)   NULL,
    [ADRESSE_LIVRAISON]                    NVARCHAR (MAX) NULL,
    [CONTACT]                              NVARCHAR (MAX) NULL,
    [TEL_CONTACT]                          NVARCHAR (20)  NULL,
    [REMARQUE]                             NVARCHAR (MAX) NULL,
    [VALIDE]                               BIT            CONSTRAINT [DF_COMMANDE_FOURNISSEUR_VALIDE] DEFAULT ('0') NOT NULL,
    [USER_VALIDATION]                      DECIMAL (18)   NULL,
    [DATE_VALIDATION]                      DATETIME       NULL,
    CONSTRAINT [PK_COMMANDE_FOURNISSEUR] PRIMARY KEY CLUSTERED ([CODE_COMMANDE_FOURNISSEUR] ASC),
    CONSTRAINT [FK_COMMANDE_FOURNISSEUR_FOURNISSEUR] FOREIGN KEY ([CODE_FOURNISSEUR]) REFERENCES [dbo].[FOURNISSEUR] ([CODE_FOURNISSEUR]),
    CONSTRAINT [FK_COMMANDE_FOURNISSEUR_UTILISATEUR] FOREIGN KEY ([CODE_USER]) REFERENCES [dbo].[UTILISATEUR] ([CODE_USER])
);


GO
ALTER TABLE [dbo].[COMMANDE_FOURNISSEUR] NOCHECK CONSTRAINT [FK_COMMANDE_FOURNISSEUR_FOURNISSEUR];


GO
ALTER TABLE [dbo].[COMMANDE_FOURNISSEUR] NOCHECK CONSTRAINT [FK_COMMANDE_FOURNISSEUR_UTILISATEUR];

