CREATE TABLE [dbo].[COMMANDE] (
    [CODE_COMMANDE]            NVARCHAR (25) NOT NULL,
    [CODE_CLIENT]              DECIMAL (18)  NOT NULL,
    [DATE_COMMANDE]            DATETIME      NOT NULL,
    [PRIORITE_COMMANDE]        BIT           NOT NULL,
    [CODE_USER]                DECIMAL (18)  NOT NULL,
    [DATE_EXPIRATION_COMMANDE] DATETIME      NULL,
    [REGLEE]                   BIT           NULL,
    CONSTRAINT [PK_COMMANDE] PRIMARY KEY CLUSTERED ([CODE_COMMANDE] ASC),
    CONSTRAINT [FK_COMMANDE_CLIENT] FOREIGN KEY ([CODE_CLIENT]) REFERENCES [dbo].[CLIENT] ([CODE_CLIENT]),
    CONSTRAINT [FK_COMMANDE_UTILISATEUR] FOREIGN KEY ([CODE_USER]) REFERENCES [dbo].[UTILISATEUR] ([CODE_USER])
);


GO
ALTER TABLE [dbo].[COMMANDE] NOCHECK CONSTRAINT [FK_COMMANDE_CLIENT];


GO
ALTER TABLE [dbo].[COMMANDE] NOCHECK CONSTRAINT [FK_COMMANDE_UTILISATEUR];

