CREATE TABLE [dbo].[COMPTE_CLIENT] (
    [CODE_COMPTE_CLIENT] DECIMAL (18)    NOT NULL,
    [NUM_COMPTE_CLIENT]  NVARCHAR (450)  NOT NULL,
    [TOTAl_CREDIT_CLT]   DECIMAL (18, 3) NULL,
    [TOTAL_PAYE_CLT]     DECIMAL (18, 3) NULL,
    [CODE_CLIENT]        DECIMAL (18)    NOT NULL,
    CONSTRAINT [PK_COMPTE_CLIENT] PRIMARY KEY CLUSTERED ([CODE_COMPTE_CLIENT] ASC),
    CONSTRAINT [FK_COMPTE_CLIENT_CLIENT] FOREIGN KEY ([CODE_CLIENT]) REFERENCES [dbo].[CLIENT] ([CODE_CLIENT])
);


GO
ALTER TABLE [dbo].[COMPTE_CLIENT] NOCHECK CONSTRAINT [FK_COMPTE_CLIENT_CLIENT];

