CREATE TABLE [dbo].[CONNECTED_MACHINES] (
    [CODE_CONNEXION] DECIMAL (18)   NOT NULL,
    [Nom_machine]    NVARCHAR (MAX) NULL,
    [ADRESSE_IP]     NCHAR (10)     NULL,
    [PRENOM_USER]    NVARCHAR (MAX) NOT NULL,
    [CODE_USER]      DECIMAL (18)   NOT NULL,
    [NOM_USER]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CONNECTED_MACHINES] PRIMARY KEY CLUSTERED ([CODE_CONNEXION] ASC)
);

