CREATE TABLE [dbo].[EMPLOYE] (
    [CODE_EMPLOYE]          DECIMAL (18)   NOT NULL,
    [NOM_EMPLOYE]           NVARCHAR (MAX) NOT NULL,
    [PRENOM_EMPLOYE]        NVARCHAR (MAX) NOT NULL,
    [DATE_NAIS_EMPLOYE]     DATETIME       NULL,
    [ADRESSE_EMPLOYE]       NVARCHAR (MAX) NULL,
    [TEL_EMPLOYE]           NVARCHAR (MAX) NULL,
    [EMAIL_EMPLOYE]         NVARCHAR (MAX) NULL,
    [DATE_EMBAUCHE_EMPLOYE] DATETIME       NOT NULL,
    [CODE_SOCIETE]          DECIMAL (18)   NOT NULL,
    [ETAT_EMPLOYE]          BIT            NULL,
    CONSTRAINT [PK_EMPLOYE] PRIMARY KEY CLUSTERED ([CODE_EMPLOYE] ASC),
    CONSTRAINT [FK_EMPLOYE_SOCIETE] FOREIGN KEY ([CODE_SOCIETE]) REFERENCES [dbo].[SOCIETE] ([CODE_SOCIETE])
);


GO
ALTER TABLE [dbo].[EMPLOYE] NOCHECK CONSTRAINT [FK_EMPLOYE_SOCIETE];

