CREATE TABLE [dbo].[EQUIPEMENT] (
    [CODE_EQP]              DECIMAL (18)  IDENTITY (1, 1) NOT NULL,
    [LIBELLE_EQP]           NVARCHAR (50) CONSTRAINT [DF_EQUIPEMENT_LIBELLE_EQP] DEFAULT ('') NOT NULL,
    [NUM_SERIE]             NVARCHAR (50) CONSTRAINT [DF_EQUIPEMENT_NUM_SERIE] DEFAULT ('') NOT NULL,
    [DATE_FAB_EQP]          DATETIME      CONSTRAINT [DF_EQUIPEMENT_DATE_FAB_EQP] DEFAULT ('01/01/1900') NOT NULL,
    [DATE_MISE_SERVICE_EQP] DATETIME      CONSTRAINT [DF_EQUIPEMENT_DATE_MISE_SERVICE_EQP] DEFAULT ('01/01/1900') NOT NULL,
    [FABRIQUANT]            NVARCHAR (50) CONSTRAINT [DF_EQUIPEMENT_FABRIQUANT] DEFAULT ('') NOT NULL,
    [CODE_CLIENT]           DECIMAL (18)  NOT NULL,
    CONSTRAINT [PK_EQUIPEMENT] PRIMARY KEY CLUSTERED ([CODE_EQP] ASC)
);

