CREATE TABLE [dbo].[FACTURE] (
    [CODE_FACTURE]          NVARCHAR (25)   NOT NULL,
    [DATE_FACTURE]          DATETIME        NOT NULL,
    [CODE_CLIENT]           DECIMAL (18)    NOT NULL,
    [MONTANT_HT_FACTURE]    DECIMAL (18, 3) NOT NULL,
    [MONTANT_TVA]           DECIMAL (18, 3) NOT NULL,
    [MONTANT_TTC]           DECIMAL (18, 3) NOT NULL,
    [TAUX_REMISE]           DECIMAL (4, 2)  NOT NULL,
    [MONTANT_BASE]          DECIMAL (18, 3) NOT NULL,
    [TIMBRE_FACTURE]        DECIMAL (18, 3) NOT NULL,
    [MONTANT_TOTAL_FACTURE] DECIMAL (18, 3) NOT NULL,
    [MONTANT_LETTRE]        NVARCHAR (MAX)  NOT NULL,
    [ANNULATION_FACTURE]    BIT             NOT NULL,
    [REGLER]                NVARCHAR (MAX)  NOT NULL,
    [CREDIT]                DECIMAL (18, 3) NULL,
    [MAGASIN]               DECIMAL (18)    NULL,
    [CODE_USER]             DECIMAL (18)    NOT NULL,
    [PRENOM_USER]           NVARCHAR (MAX)  NOT NULL,
    [NOM_USER]              NVARCHAR (MAX)  NOT NULL,
    [REMARQUE]              NVARCHAR (MAX)  NULL,
    [REMISE]                DECIMAL (18, 3) CONSTRAINT [DF_FACTURE_REMISE] DEFAULT ('0') NOT NULL,
    CONSTRAINT [PK_FACTURE] PRIMARY KEY CLUSTERED ([CODE_FACTURE] ASC)
);

