CREATE TABLE [dbo].[FACTURATION] (
    [CODE_B_LIV]       NVARCHAR (20) NOT NULL,
    [CODE_FACTURE]     NVARCHAR (25) NOT NULL,
    [DATE_FACTURATION] DATETIME      NOT NULL,
    CONSTRAINT [FK_FACTURATION_BON_DE_LIVRAISON] FOREIGN KEY ([CODE_B_LIV]) REFERENCES [dbo].[BON_DE_LIVRAISON] ([CODE_B_LIV]),
    CONSTRAINT [FK_FACTURATION_FACTURE] FOREIGN KEY ([CODE_FACTURE]) REFERENCES [dbo].[FACTURE] ([CODE_FACTURE])
);


GO
ALTER TABLE [dbo].[FACTURATION] NOCHECK CONSTRAINT [FK_FACTURATION_BON_DE_LIVRAISON];


GO
ALTER TABLE [dbo].[FACTURATION] NOCHECK CONSTRAINT [FK_FACTURATION_FACTURE];

