CREATE TABLE [dbo].[FACTURATION_FOURNISSEUR] (
    [CODE_FACTURE_FOURNISSEUR]  NVARCHAR (20) NOT NULL,
    [CODE_COMMANDE_FOURNISSEUR] NVARCHAR (12) NOT NULL,
    CONSTRAINT [FK_FACTURATION_FOURNISSEUR_COMMANDE_FOURNISSEUR] FOREIGN KEY ([CODE_COMMANDE_FOURNISSEUR]) REFERENCES [dbo].[COMMANDE_FOURNISSEUR] ([CODE_COMMANDE_FOURNISSEUR]),
    CONSTRAINT [FK_FACTURATION_FOURNISSEUR_FACTURE_FOURNISSEUR] FOREIGN KEY ([CODE_FACTURE_FOURNISSEUR]) REFERENCES [dbo].[FACTURE_FOURNISSEUR] ([CODE_FACTURE_FOURNISSEUR])
);


GO
ALTER TABLE [dbo].[FACTURATION_FOURNISSEUR] NOCHECK CONSTRAINT [FK_FACTURATION_FOURNISSEUR_COMMANDE_FOURNISSEUR];


GO
ALTER TABLE [dbo].[FACTURATION_FOURNISSEUR] NOCHECK CONSTRAINT [FK_FACTURATION_FOURNISSEUR_FACTURE_FOURNISSEUR];

