CREATE TABLE [dbo].[FAM_COMPTA] (
    [FAC_ID]        DECIMAL (18)  IDENTITY (1, 1) NOT NULL,
    [FAC_LIBELLE]   NVARCHAR (50) NOT NULL,
    [FAC_CPT_ACHAT] NVARCHAR (20) NOT NULL,
    [FAC_CPT_VENTE] NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_FAM_COMPTA] PRIMARY KEY CLUSTERED ([FAC_ID] ASC)
);

