CREATE TABLE [dbo].[FAMILLE] (
    [CODE_FAMILLE]        DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [REF_FAMILLE]         NVARCHAR (50)  NULL,
    [DESIGNATION_FAMILLE] NVARCHAR (50)  NULL,
    [DESCRIPTION_FAMILLE] NVARCHAR (MAX) NULL,
    [PARENT]              DECIMAL (18)   NULL,
    [TYPE]                NCHAR (1)      NULL,
    CONSTRAINT [PK_FAMILLE] PRIMARY KEY CLUSTERED ([CODE_FAMILLE] ASC)
);

