CREATE TABLE [dbo].[FOURNISSEUR] (
    [CODE_FOURNISSEUR]     DECIMAL (18)   NOT NULL,
    [REF_FOURNISSEUR]      NVARCHAR (MAX) NULL,
    [RS_FOURNISSEUR]       NVARCHAR (MAX) NOT NULL,
    [ADRESSE_FOURNISSEUR]  NVARCHAR (MAX) NULL,
    [TEL_FOURNISSEUR]      NVARCHAR (MAX) NULL,
    [FAX_FOURNISSEUR]      NVARCHAR (MAX) NULL,
    [EMAIL_FOURNISSEUR]    NVARCHAR (MAX) NULL,
    [SITE_WEB_FOURNISSEUR] NVARCHAR (MAX) NULL,
    [RIB_FOURNISSEUR]      NVARCHAR (MAX) NULL,
    [CODE_TVA_FOURNISSEUR] NVARCHAR (MAX) NULL,
    [RETENUE_SOURCE]       DECIMAL (4, 2) CONSTRAINT [DF_FOURNISSEUR_RETENUE_SOURCE] DEFAULT ('0') NOT NULL,
    CONSTRAINT [PK_FOURNISSEUR] PRIMARY KEY CLUSTERED ([CODE_FOURNISSEUR] ASC)
);

