CREATE TABLE [dbo].[INVENTAIRE] (
    [CODE_INVENTAIRE]       DECIMAL (18) NOT NULL,
    [DATE_DEBUT_INVENTAIRE] DATETIME     NULL,
    [DATE_FIN_INVENTAIRE]   DATETIME     NULL,
    [CODE_MAG]              DECIMAL (18) NULL,
    [UTILISATEUR_CREAT_INV] DECIMAL (18) NULL,
    [UTILISATEUR_FERM_INV]  DECIMAL (18) NULL,
    CONSTRAINT [PK_INVENTAIRE] PRIMARY KEY CLUSTERED ([CODE_INVENTAIRE] ASC)
);

