CREATE TABLE [dbo].[LG_BON_LIVRAISON] (
    [CODE_B_LIV]      NVARCHAR (20)   NOT NULL,
    [CODE_COMMANDE]   NVARCHAR (25)   NOT NULL,
    [TYPE_PIECE]      NVARCHAR (10)   CONSTRAINT [DF_LG_BON_LIVRAISON_TYPE_PIECE] DEFAULT ('') NOT NULL,
    [CODE_ARTICLE]    DECIMAL (18)    NOT NULL,
    [UNITE]           NVARCHAR (25)   CONSTRAINT [DF_LG_BON_LIVRAISON_UNITE] DEFAULT ('') NOT NULL,
    [QTE_LIGNE_B_LIV] DECIMAL (18)    NOT NULL,
    [PRIX_HT_B_LIV]   DECIMAL (18, 3) NOT NULL,
    [TVA_B_LIV]       DECIMAL (18, 2) NOT NULL,
    [PRIX_TOTAL_HT]   DECIMAL (18, 3) NULL,
    [PRIX_U_TTC]      DECIMAL (18, 3) NULL,
    [PRIX_TOTAL_TTC]  DECIMAL (18, 3) NULL,
    [REMISE]          DECIMAL (18, 3) NULL,
    [CODE_FACTURE]    NVARCHAR (25)   CONSTRAINT [DF_LG_BON_LIVRAISON_CODE_FACTURE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_LG_BON_LIVRAISON] PRIMARY KEY CLUSTERED ([CODE_B_LIV] ASC, [CODE_COMMANDE] ASC, [TYPE_PIECE] ASC, [CODE_ARTICLE] ASC),
    CONSTRAINT [FK_LG_BON_LIVRAISON_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE]),
    CONSTRAINT [FK_LG_BON_LIVRAISON_BON_DE_LIVRAISON] FOREIGN KEY ([CODE_B_LIV]) REFERENCES [dbo].[BON_DE_LIVRAISON] ([CODE_B_LIV]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[LG_BON_LIVRAISON] NOCHECK CONSTRAINT [FK_LG_BON_LIVRAISON_BON_DE_LIVRAISON];

