CREATE TABLE [dbo].[LG_BR_FR] (
    [CODE_BRECEP]    DECIMAL (18)    CONSTRAINT [DF_LG_BR_FR_CODE_BRECEP] DEFAULT ((0)) NOT NULL,
    [CODE_BR_FR]     NVARCHAR (12)   NOT NULL,
    [CODE_ARTICLE]   DECIMAL (18)    NOT NULL,
    [QTE_LG_BR_FR]   DECIMAL (18, 3) NOT NULL,
    [UNITE]          NVARCHAR (25)   CONSTRAINT [DF_LG_BR_FR_UNITE] DEFAULT ('') NOT NULL,
    [PRIX_ART_BR_FR] DECIMAL (18, 3) NOT NULL,
    [TVA]            DECIMAL (18, 2) CONSTRAINT [DF_LG_BR_FR_TVA] DEFAULT ((0)) NOT NULL,
    [REMISE]         DECIMAL (18, 2) CONSTRAINT [DF_LG_BR_FR_REMISE] DEFAULT ('0') NOT NULL,
    [FODEC]          DECIMAL (18, 2) CONSTRAINT [DF_LG_BR_FR_FODEC] DEFAULT ('0') NOT NULL,
    [CODE_CMD_FR]    NVARCHAR (25)   CONSTRAINT [DF_LG_BR_FR_CODE_CMD_FR] DEFAULT ('') NOT NULL,
    [CODE_FACT_FR]   NVARCHAR (25)   CONSTRAINT [DF_LG_BR_FR_CODE_FACT_FR] DEFAULT ('') NOT NULL,
    CONSTRAINT [FK_LG_BR_FR_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE])
);

