CREATE TABLE [dbo].[LG_CMD_FR] (
    [CODE_COMMANDE_FOURNISSEUR] NVARCHAR (12)   NOT NULL,
    [CODE_ARTICLE]              DECIMAL (18)    NOT NULL,
    [QTE]                       DECIMAL (18, 3) CONSTRAINT [DF_LG_CMD_FR_QTE] DEFAULT ('0') NOT NULL,
    [PRIX_HT]                   DECIMAL (18, 3) CONSTRAINT [DF_LG_CMD_FR_PRIX_HT] DEFAULT ('0') NOT NULL,
    [REMISE]                    DECIMAL (18, 3) CONSTRAINT [DF_LG_CMD_FR_REMISE] DEFAULT ('0') NOT NULL,
    [FODEC]                     DECIMAL (18, 3) CONSTRAINT [DF_LG_CMD_FR_FODEC] DEFAULT ('0') NOT NULL,
    [TAUX_TVA]                  DECIMAL (18, 2) CONSTRAINT [DF_LG_CMD_FR_TAUX_TVA] DEFAULT ('0') NOT NULL,
    [UNITE]                     NVARCHAR (20)   CONSTRAINT [DF_LG_CMD_FR_UNITE] DEFAULT ('') NOT NULL,
    [CODE_UNITE_ARTICLE]        DECIMAL (18)    NULL,
    CONSTRAINT [PK_LG_CMD_FR] PRIMARY KEY CLUSTERED ([CODE_COMMANDE_FOURNISSEUR] ASC, [CODE_ARTICLE] ASC),
    CONSTRAINT [FK_LG_CMD_FR_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE]),
    CONSTRAINT [FK_LG_CMD_FR_COMMANDE_FOURNISSEUR] FOREIGN KEY ([CODE_COMMANDE_FOURNISSEUR]) REFERENCES [dbo].[COMMANDE_FOURNISSEUR] ([CODE_COMMANDE_FOURNISSEUR])
);


GO
ALTER TABLE [dbo].[LG_CMD_FR] NOCHECK CONSTRAINT [FK_LG_CMD_FR_COMMANDE_FOURNISSEUR];

