CREATE TABLE [dbo].[LG_FACT_FR] (
    [CODE_FACTURE_FOURNISSEUR] NVARCHAR (20)   NOT NULL,
    [CODE_ARTICLE]             DECIMAL (18)    NOT NULL,
    [QTE]                      DECIMAL (18, 3) NOT NULL,
    [UNITE]                    NVARCHAR (10)   NOT NULL,
    [PRIX_HT]                  DECIMAL (18, 3) NOT NULL,
    [REMISE]                   DECIMAL (18, 3) NOT NULL,
    [FODEC]                    DECIMAL (18, 3) NOT NULL,
    [TAUX_TVA]                 DECIMAL (18, 3) NOT NULL,
    [CODE_BR_FR]               DECIMAL (18)    NOT NULL,
    [CODE_CMD_FR]              NVARCHAR (20)   CONSTRAINT [DF_LG_FACT_FR_CODE_CMD_FR] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_LG_FACT_FR_1] PRIMARY KEY CLUSTERED ([CODE_FACTURE_FOURNISSEUR] ASC, [CODE_ARTICLE] ASC, [CODE_BR_FR] ASC, [CODE_CMD_FR] ASC),
    CONSTRAINT [FK_LG_FACT_FR_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE])
);

