CREATE TABLE [dbo].[LG_TC] (
    [CODE_TC]      NVARCHAR (25)   NOT NULL,
    [CODE_ARTICLE] DECIMAL (18)    NOT NULL,
    [QTE]          DECIMAL (18, 3) NOT NULL,
    [UNITE]        NVARCHAR (50)   NOT NULL,
    [PRIX_HT]      DECIMAL (18, 3) NOT NULL,
    [TAUX_REMISE]  DECIMAL (18, 3) NOT NULL,
    [TVA]          DECIMAL (18, 3) NOT NULL,
    [PRIX_TTC]     DECIMAL (18, 3) NOT NULL,
    CONSTRAINT [PK_LG_TC] PRIMARY KEY CLUSTERED ([CODE_TC] ASC, [CODE_ARTICLE] ASC),
    CONSTRAINT [FK_LG_TC_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE])
);

