CREATE TABLE [dbo].[LIGNE_BRETOUR_CLIENT] (
    [CODE_BRETOUR_CLIENT] NVARCHAR (20)   NOT NULL,
    [CODE_ARTICLE]        DECIMAL (18)    NOT NULL,
    [QTE_BRETOUR_CLIENT]  DECIMAL (18, 3) NULL,
    [PRIX_BRETOUR_CLIENT] DECIMAL (18, 3) NULL,
    CONSTRAINT [PK_LIGNE_BRETOUR_CLIENT] PRIMARY KEY CLUSTERED ([CODE_BRETOUR_CLIENT] ASC, [CODE_ARTICLE] ASC),
    CONSTRAINT [FK_LIGNE_BRETOUR_CLIENT_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE])
);

