CREATE TABLE [dbo].[LIGNE_FACTURE] (
    [CODE_FACTURE]    NVARCHAR (25)   NOT NULL,
    [CODE_ARTICLE]    DECIMAL (18)    NOT NULL,
    [CODE_BL]         NVARCHAR (25)   CONSTRAINT [DF_LIGNE_FACTURE_CODE_BL] DEFAULT ('') NOT NULL,
    [TYPE_PIECE]      NVARCHAR (10)   CONSTRAINT [DF_LIGNE_FACTURE_TYPE_PIECE] DEFAULT ('') NOT NULL,
    [UNITE]           NVARCHAR (50)   CONSTRAINT [DF_LIGNE_FACTURE_UNITE] DEFAULT ('') NOT NULL,
    [QTE]             DECIMAL (18, 3) NOT NULL,
    [TVA_ARTICLE]     DECIMAL (5, 2)  NOT NULL,
    [PRIX_HT_ARTICLE] DECIMAL (18, 3) NOT NULL,
    [PRIX_TOTAL_HT]   DECIMAL (18, 3) NOT NULL,
    [PRIX_U_TTC]      DECIMAL (18, 3) NOT NULL,
    [PRIX_TOTAL_TTC]  DECIMAL (18, 3) NOT NULL,
    [REMISE]          DECIMAL (18, 3) NOT NULL,
    [PRIX_FACTURE]    DECIMAL (18, 3) NOT NULL,
    CONSTRAINT [PK_LIGNE_FACTURE_1] PRIMARY KEY CLUSTERED ([CODE_FACTURE] ASC, [CODE_ARTICLE] ASC, [CODE_BL] ASC, [TYPE_PIECE] ASC),
    CONSTRAINT [FK_LIGNE_FACTURE_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE]),
    CONSTRAINT [FK_LIGNE_FACTURE_FACTURE] FOREIGN KEY ([CODE_FACTURE]) REFERENCES [dbo].[FACTURE] ([CODE_FACTURE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[LIGNE_FACTURE] NOCHECK CONSTRAINT [FK_LIGNE_FACTURE_FACTURE];

