CREATE TABLE [dbo].[LIGNE_INVENTAIRE] (
    [CODE_INVENTAIRE] DECIMAL (18)    NOT NULL,
    [CODE_ARTICLE]    DECIMAL (18)    NOT NULL,
    [QTE_INVENTAIRE]  DECIMAL (18, 3) NULL,
    [QTE_STOCK]       DECIMAL (18, 3) NULL,
    [QTE_ACHAT]       DECIMAL (18, 3) NULL,
    [QTE_VENTE]       DECIMAL (18, 3) NULL,
    [QTE_RETOUR]      DECIMAL (18, 3) NULL,
    CONSTRAINT [PK_LIGNE_INVENTAIRE] PRIMARY KEY CLUSTERED ([CODE_INVENTAIRE] ASC, [CODE_ARTICLE] ASC),
    CONSTRAINT [FK_LIGNE_INVENTAIRE_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE])
);

