CREATE TABLE [dbo].[LIGNE_COMMANDE] (
    [CODE_ARTICLE]       DECIMAL (18)    NOT NULL,
    [CODE_COMMANDE]      NVARCHAR (25)   NOT NULL,
    [QTE_LIGNE_COMMANDE] DECIMAL (18, 3) NULL,
    [PRIX_HT_COMMANDE]   DECIMAL (18, 3) NULL,
    [TVA_COMMANDE]       DECIMAL (18, 2) NULL,
    [QTE_LIVRE]          DECIMAL (18, 3) NULL,
    CONSTRAINT [PK_LIGNE_COMMANDE] PRIMARY KEY CLUSTERED ([CODE_ARTICLE] ASC, [CODE_COMMANDE] ASC),
    CONSTRAINT [FK_LIGNE_COMMANDE_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE]),
    CONSTRAINT [FK_LIGNE_COMMANDE_COMMANDE] FOREIGN KEY ([CODE_COMMANDE]) REFERENCES [dbo].[COMMANDE] ([CODE_COMMANDE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[LIGNE_COMMANDE] NOCHECK CONSTRAINT [FK_LIGNE_COMMANDE_COMMANDE];

