CREATE TABLE [dbo].[LIVRAISON] (
    [CODE_B_LIV]     NVARCHAR (20)  NOT NULL,
    [PRENOM_EMPLOYE] NVARCHAR (MAX) NULL,
    [CODE_EMPLOYE]   DECIMAL (18)   NOT NULL,
    [NOM_EMPLOYE]    NVARCHAR (MAX) NULL,
    [DATE_LIVRAISON] DATETIME       NOT NULL,
    CONSTRAINT [FK_LIVRAISON_BON_DE_LIVRAISON] FOREIGN KEY ([CODE_B_LIV]) REFERENCES [dbo].[BON_DE_LIVRAISON] ([CODE_B_LIV]),
    CONSTRAINT [FK_LIVRAISON_EMPLOYE] FOREIGN KEY ([CODE_EMPLOYE]) REFERENCES [dbo].[EMPLOYE] ([CODE_EMPLOYE])
);


GO
ALTER TABLE [dbo].[LIVRAISON] NOCHECK CONSTRAINT [FK_LIVRAISON_BON_DE_LIVRAISON];


GO
ALTER TABLE [dbo].[LIVRAISON] NOCHECK CONSTRAINT [FK_LIVRAISON_EMPLOYE];

