CREATE TABLE [dbo].[MARQUE] (
    [CODE_MARQUE]        DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [REF_MARQUE]         NVARCHAR (50)  NULL,
    [DESIGNATION_MARQUE] NVARCHAR (50)  NULL,
    [DESCRIPTION_MARQUE] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_MARQUE] PRIMARY KEY CLUSTERED ([CODE_MARQUE] ASC)
);

