CREATE TABLE [dbo].[MENU] (
    [CODE_MENU]        NVARCHAR (50)  NOT NULL,
    [DESIGNATION_MENU] NVARCHAR (MAX) NULL,
    [DESCRIPTION_MENU] NVARCHAR (MAX) NULL,
    [MENU_PARENT]      NVARCHAR (50)  NULL,
    CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED ([CODE_MENU] ASC)
);

