CREATE TABLE [dbo].[PRIVILEGE_UTILISATEUR] (
    [CODE_PRIVILEGE]       DECIMAL (18) NOT NULL,
    [COMMANDE_CLIENT_PRIV] BIT          NULL,
    [COMMANDE_FOURN_PRIV]  BIT          NULL,
    [FACTURE_CLIENT_PRIV]  BIT          NULL,
    [FACTURE_FOURN_PRIV]   BIT          NULL,
    [COMPTE_USER_PRIV]     BIT          NULL,
    [AJOUT_STOCK_PRIV]     BIT          NULL,
    [CONSULT_STOCK_PRIV]   BIT          NULL,
    CONSTRAINT [PK_PRIVILEGE_UTILISATEUR] PRIMARY KEY CLUSTERED ([CODE_PRIVILEGE] ASC)
);

