CREATE TABLE [dbo].[STOCK] (
    [CODE_MAG]     DECIMAL (18) NOT NULL,
    [CODE_ARTICLE] DECIMAL (18) NOT NULL,
    [QTTE_STOCK]   DECIMAL (18) NOT NULL,
    CONSTRAINT [PK_STOCK] PRIMARY KEY CLUSTERED ([CODE_MAG] ASC, [CODE_ARTICLE] ASC),
    CONSTRAINT [FK_STOCK_ARTICLE] FOREIGN KEY ([CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE]),
    CONSTRAINT [FK_STOCK_MAGAZIN] FOREIGN KEY ([CODE_MAG]) REFERENCES [dbo].[MAGAZIN] ([CODE_MAG]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[STOCK] NOCHECK CONSTRAINT [FK_STOCK_MAGAZIN];

