CREATE TABLE [dbo].[TARIF_VENTE] (
    [TRV_ID]            DECIMAL (18)    IDENTITY (1, 1) NOT NULL,
    [TRV_LIBELLE]       NVARCHAR (MAX)  NULL,
    [TRV_CODE_ARTICLE]  DECIMAL (18)    NULL,
    [TRV_CODE_CLIENT]   DECIMAL (18)    NULL,
    [TRV_CODE_UNITE]    DECIMAL (18)    NOT NULL,
    [TRV_PRIX_HT]       DECIMAL (18, 3) NOT NULL,
    [TRV_TX_REMISE]     DECIMAL (18, 3) NOT NULL,
    [TRV_DEBUT_VALID]   DATETIME        NOT NULL,
    [TRV_FIN_VALID]     DATETIME        NOT NULL,
    [TRV_DATE_CREATION] DATETIME        NULL,
    [TRV_CREATEUR]      DECIMAL (18)    NULL,
    [TRV_DATE_MODIF]    DATETIME        NULL,
    [TRV_MODIFICATEUR]  DECIMAL (18)    NULL,
    CONSTRAINT [PK_TARIF_VENTE] PRIMARY KEY CLUSTERED ([TRV_ID] ASC),
    CONSTRAINT [FK_TARIF_VENTE_ARTICLE] FOREIGN KEY ([TRV_CODE_ARTICLE]) REFERENCES [dbo].[ARTICLE] ([CODE_ARTICLE]),
    CONSTRAINT [FK_TARIF_VENTE_CLIENT] FOREIGN KEY ([TRV_CODE_CLIENT]) REFERENCES [dbo].[CLIENT] ([CODE_CLIENT]),
    CONSTRAINT [FK_TARIF_VENTE_UTILISATEUR] FOREIGN KEY ([TRV_CREATEUR]) REFERENCES [dbo].[UTILISATEUR] ([CODE_USER]),
    CONSTRAINT [FK_TARIF_VENTE_UTILISATEUR1] FOREIGN KEY ([TRV_MODIFICATEUR]) REFERENCES [dbo].[UTILISATEUR] ([CODE_USER])
);

