CREATE TABLE [dbo].[UTILISATEUR] (
    [CODE_USER]          DECIMAL (18)   NOT NULL,
    [NOM_USER]           NVARCHAR (MAX) NOT NULL,
    [PRENOM_USER]        NVARCHAR (MAX) NOT NULL,
    [PHOTO_USER]         IMAGE          NULL,
    [LOGIN_USER]         NVARCHAR (MAX) NOT NULL,
    [PASSWORD_USER]      NVARCHAR (MAX) NOT NULL,
    [ETAT_USER]          BIT            NOT NULL,
    [CODE_SOCIETE]       DECIMAL (18)   NOT NULL,
    [CODE_FONCTION_USER] DECIMAL (18)   NOT NULL,
    CONSTRAINT [PK_UTILISATEUR] PRIMARY KEY CLUSTERED ([CODE_USER] ASC),
    CONSTRAINT [FK_UTILISATEUR_FONCTION_UTILISATEUR] FOREIGN KEY ([CODE_FONCTION_USER]) REFERENCES [dbo].[FONCTION_UTILISATEUR] ([CODE_FONCTION_USER]) ON UPDATE CASCADE,
    CONSTRAINT [FK_UTILISATEUR_SOCIETE] FOREIGN KEY ([CODE_SOCIETE]) REFERENCES [dbo].[SOCIETE] ([CODE_SOCIETE])
);


GO
ALTER TABLE [dbo].[UTILISATEUR] NOCHECK CONSTRAINT [FK_UTILISATEUR_FONCTION_UTILISATEUR];


GO
ALTER TABLE [dbo].[UTILISATEUR] NOCHECK CONSTRAINT [FK_UTILISATEUR_SOCIETE];

