//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CHM_CLIENT_APP.CHMSTAT {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CHMSTATSoap", Namespace="http://192.168.1.213:10001/")]
    public partial class CHMSTAT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback closeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SELECT_NB_ARTICLE_EN_RUPTURE_STOCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback SELECT_NB_FACTUREOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CHMSTAT() {
            this.Url = global::CHM_CLIENT_APP.Properties.Settings.Default.CHM_CLIENT_APP_CHMSTAT_CHMSTAT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConnectionCompletedEventHandler ConnectionCompleted;
        
        /// <remarks/>
        public event closeCompletedEventHandler closeCompleted;
        
        /// <remarks/>
        public event getDateCompletedEventHandler getDateCompleted;
        
        /// <remarks/>
        public event SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompletedEventHandler SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompleted;
        
        /// <remarks/>
        public event SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompletedEventHandler SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompleted;
        
        /// <remarks/>
        public event SELECT_NB_FACTURECompletedEventHandler SELECT_NB_FACTURECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/Connection", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Connection() {
            this.Invoke("Connection", new object[0]);
        }
        
        /// <remarks/>
        public void ConnectionAsync() {
            this.ConnectionAsync(null);
        }
        
        /// <remarks/>
        public void ConnectionAsync(object userState) {
            if ((this.ConnectionOperationCompleted == null)) {
                this.ConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectionOperationCompleted);
            }
            this.InvokeAsync("Connection", new object[0], this.ConnectionOperationCompleted, userState);
        }
        
        private void OnConnectionOperationCompleted(object arg) {
            if ((this.ConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnectionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/close", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void close() {
            this.Invoke("close", new object[0]);
        }
        
        /// <remarks/>
        public void closeAsync() {
            this.closeAsync(null);
        }
        
        /// <remarks/>
        public void closeAsync(object userState) {
            if ((this.closeOperationCompleted == null)) {
                this.closeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncloseOperationCompleted);
            }
            this.InvokeAsync("close", new object[0], this.closeOperationCompleted, userState);
        }
        
        private void OncloseOperationCompleted(object arg) {
            if ((this.closeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.closeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/getDate", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime getDate() {
            object[] results = this.Invoke("getDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void getDateAsync() {
            this.getDateAsync(null);
        }
        
        /// <remarks/>
        public void getDateAsync(object userState) {
            if ((this.getDateOperationCompleted == null)) {
                this.getDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDateOperationCompleted);
            }
            this.InvokeAsync("getDate", new object[0], this.getDateOperationCompleted, userState);
        }
        
        private void OngetDateOperationCompleted(object arg) {
            if ((this.getDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDateCompleted(this, new getDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/SELECT_NB_ARTICLE_EN_RUPTURE_STOCK", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SELECT_NB_ARTICLE_EN_RUPTURE_STOCK() {
            object[] results = this.Invoke("SELECT_NB_ARTICLE_EN_RUPTURE_STOCK", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SELECT_NB_ARTICLE_EN_RUPTURE_STOCKAsync() {
            this.SELECT_NB_ARTICLE_EN_RUPTURE_STOCKAsync(null);
        }
        
        /// <remarks/>
        public void SELECT_NB_ARTICLE_EN_RUPTURE_STOCKAsync(object userState) {
            if ((this.SELECT_NB_ARTICLE_EN_RUPTURE_STOCKOperationCompleted == null)) {
                this.SELECT_NB_ARTICLE_EN_RUPTURE_STOCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSELECT_NB_ARTICLE_EN_RUPTURE_STOCKOperationCompleted);
            }
            this.InvokeAsync("SELECT_NB_ARTICLE_EN_RUPTURE_STOCK", new object[0], this.SELECT_NB_ARTICLE_EN_RUPTURE_STOCKOperationCompleted, userState);
        }
        
        private void OnSELECT_NB_ARTICLE_EN_RUPTURE_STOCKOperationCompleted(object arg) {
            if ((this.SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompleted(this, new SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCK", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCK() {
            object[] results = this.Invoke("SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCK", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKAsync() {
            this.SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKAsync(null);
        }
        
        /// <remarks/>
        public void SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKAsync(object userState) {
            if ((this.SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKOperationCompleted == null)) {
                this.SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKOperationCompleted);
            }
            this.InvokeAsync("SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCK", new object[0], this.SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKOperationCompleted, userState);
        }
        
        private void OnSELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKOperationCompleted(object arg) {
            if ((this.SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompleted(this, new SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.1.213:10001/SELECT_NB_FACTURE", RequestNamespace="http://192.168.1.213:10001/", ResponseNamespace="http://192.168.1.213:10001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SELECT_NB_FACTURE() {
            object[] results = this.Invoke("SELECT_NB_FACTURE", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SELECT_NB_FACTUREAsync() {
            this.SELECT_NB_FACTUREAsync(null);
        }
        
        /// <remarks/>
        public void SELECT_NB_FACTUREAsync(object userState) {
            if ((this.SELECT_NB_FACTUREOperationCompleted == null)) {
                this.SELECT_NB_FACTUREOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSELECT_NB_FACTUREOperationCompleted);
            }
            this.InvokeAsync("SELECT_NB_FACTURE", new object[0], this.SELECT_NB_FACTUREOperationCompleted, userState);
        }
        
        private void OnSELECT_NB_FACTUREOperationCompleted(object arg) {
            if ((this.SELECT_NB_FACTURECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SELECT_NB_FACTURECompleted(this, new SELECT_NB_FACTURECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConnectionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void closeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getDateCompletedEventHandler(object sender, getDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompletedEventHandler(object sender, SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SELECT_NB_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompletedEventHandler(object sender, SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SELECT_DETAIL_ARTICLE_EN_RUPTURE_STOCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SELECT_NB_FACTURECompletedEventHandler(object sender, SELECT_NB_FACTURECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SELECT_NB_FACTURECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SELECT_NB_FACTURECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591