//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHM_CLIENT_APP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Documents and Settings\\DELL\\Mes doc" +
            "uments\\Visual Studio 2005\\Projects\\CHM_GESTION_COMERCIALE\\CHM_SERVER\\bin\\Debug\\G" +
            "ESTION_COMMERCIALE.mdf\";Integrated Security=True;Connect Timeout=30;User Instanc" +
            "e=True")]
        public string GESTION_COMMERCIALEConnectionString {
            get {
                return ((string)(this["GESTION_COMMERCIALEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.2;Initial Catalog=GC;User ID=sa;Password=miros05:")]
        public string GCConnectionString {
            get {
                return ((string)(this["GCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DBSRV\\CHM;Initial Catalog=GC;Persist Security Info=True;User ID=sa;Pa" +
            "ssword=miros05:")]
        public string GCConnectionString1 {
            get {
                return ((string)(this["GCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHMCNX.asmx")]
        public string CHM_CLIENT_APP_CHMCNX_CHMCNX {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHMCNX_CHMCNX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHMSTAT.asmx")]
        public string CHM_CLIENT_APP_CHMSTAT_CHMSTAT {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHMSTAT_CHMSTAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHM_MARQUE.asmx")]
        public string CHM_CLIENT_APP_CHMMARQUE_CHM_MARQUE {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHMMARQUE_CHM_MARQUE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHM_LIGNE_ARTICLE.asmx")]
        public string CHM_CLIENT_APP_CHM_LIGNE_ARTICLE_CHM_LIGNE_ARTICLE {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHM_LIGNE_ARTICLE_CHM_LIGNE_ARTICLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHM_FAMILLE_ARTICLE.asmx")]
        public string CHM_CLIENT_APP_CHM_FAMILLE_ARTICLE_CHM_FAMILLE_ARTICLE {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHM_FAMILLE_ARTICLE_CHM_FAMILLE_ARTICLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHMGACCES.asmx")]
        public string CHM_CLIENT_APP_CHMGACCES_CHMGACCES {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHMGACCES_CHMGACCES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHMGACCES.asmx")]
        public string CHM_CLIENT_APP_CHMGA_CHMGACCES {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHMGA_CHMGACCES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/CHM_SERIE_ARTICLE.asmx")]
        public string CHM_CLIENT_APP_CHM_SERIE_CHM_SERIE_ARTICLE {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHM_SERIE_CHM_SERIE_ARTICLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DBSRV\\CHM;Initial Catalog=GC_ENNEJMA;User ID=sa")]
        public string GC_ENNEJMAConnectionString {
            get {
                return ((string)(this["GC_ENNEJMAConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool client_fav {
            get {
                return ((bool)(this["client_fav"]));
            }
            set {
                this["client_fav"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:10001/GSWS.asmx")]
        public string CHM_CLIENT_APP_CHMGC_GSWS {
            get {
                return ((string)(this["CHM_CLIENT_APP_CHMGC_GSWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DBSRV\\CHM;Initial Catalog=GC2S2E;User ID=sa")]
        public string GC2S2EConnectionString {
            get {
                return ((string)(this["GC2S2EConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PO3-HBENSALAH;Initial Catalog=GCOM;Integrated Security=True")]
        public string GCOMConnectionString {
            get {
                return ((string)(this["GCOMConnectionString"]));
            }
        }
    }
}
